const products = [
  {
    id: 1,
    name: "Rounded Red Hat",
    price: 20.0,
    discount: null,
    brand: "Minimog",
    rating: 4.2,
    tags: ["Hats", "Fashion"],
    collection: "Accessories",
    countInStock: 85,
    colors: [
      { hex: "#ef4444", name: "Red" },
      { hex: "#facc15", name: "Yellow" },
      { hex: "#000000", name: "Black" },
    ],
    sizes: ["M", "L"],
    imagesByColor: {
      "#ef4444": "/productsImages/rounded-hat-red.png",
      "#facc15": "/productsImages/rounded-hat-yellow.png",
      "#000000": "/productsImages/rounded-hat-black.png",
    },
  },
  {
    id: 2,
    name: "Classic Linen-Blend Shirt",
    price: 55.0,
    discount: 15,
    brand: "Vagabond",
    rating: 4.6,
    tags: ["Fashion", "Denim"],
    collection: "New arrivals",
    countInStock: 0,
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#6b7280", name: "Gray" },
      { hex: "#f3f4f6", name: "White" },
    ],
    sizes: ["S", "M", "XL"],
    imagesByColor: {
      "#000000": "/productsImages/linen-blend-shirt-black.png",
      "#6b7280": "/productsImages/linen-blend-shirt-gray.png",
      "#f3f4f6": "/productsImages/linen-blend-shirt-white.png",
    },
  },
  {
    id: 3,
    name: "Long-sleeve Coat",
    price: 125.0,
    discount: null,
    brand: "Learts",
    rating: 4.9,
    tags: ["Fashion"],
    collection: "Best sellers",
    countInStock: 14,
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#1d4ed8", name: "Blue" },
    ],
    sizes: ["M", "L", "XL"],
    imagesByColor: {
      "#000000": "/productsImages/long-sleeve-coat-black.png",
      "#1d4ed8": "/productsImages/long-sleeve-coat-blue.png",
    },
  },
  {
    id: 4,
    name: "Boxy Denim Hat",
    price: 32.0,
    discount: 5,
    brand: "Brook",
    rating: 4.5,
    tags: ["Hats", "Fashion", "Beachwear"],
    collection: "Accessories",
    countInStock: 60,
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#ec4899", name: "Pink" },
    ],
    sizes: ["S", "M"],
    imagesByColor: {
      "#000000": "/productsImages/boxy-denim-hat-black.png",
      "#ec4899": "/productsImages/boxy-denim-hat-pink.png",
    },
  },
  {
    id: 5,
    name: "Linen Plain Top",
    price: 48.0,
    discount: null,
    brand: "Abby",
    rating: 4.4,
    tags: ["Fashion", "Hats"],
    collection: "All products",
    countInStock: 22,
    colors: [{ hex: "#000000", name: "Black" }],
    sizes: ["S", "M", "L"],
    imagesByColor: {
      "#000000": "/productsImages/linen-plain-top-black.png",
    },
  },
  {
    id: 6,
    name: "Oversized T-shirt",
    price: 35.0,
    discount: 10,
    brand: "Minimog",
    rating: 4.7,
    tags: ["Fashion", "Beachwear"],
    collection: "New arrivals",
    countInStock: 52,
    colors: [
      { hex: "#ef4444", name: "Red" },
      { hex: "#f3f4f6", name: "White" },
    ],
    sizes: ["S", "M", "L", "XL"],
    imagesByColor: {
      "#ef4444": "/productsImages/oversized-t-shirt-red.png",
      "#f3f4f6": "/productsImages/oversized-t-shirt-white.png",
    },
  },
  {
    id: 7,
    name: "Polarised Sunglasses",
    price: 25.0,
    discount: null,
    brand: "Brook",
    rating: 4.3,
    tags: ["Sunglasses", "Fashion", "Beachwear"],
    collection: "Accessories",
    countInStock: 18,
    colors: [
      { hex: "#0ea5e9", name: "Sky" },
      { hex: "#1d4ed8", name: "Blue" },
      { hex: "#facc15", name: "Yellow" },
    ],
    sizes: ["M"],
    imagesByColor: {
      "#0ea5e9": "/productsImages/polarised-sunglasses-sky.png",
      "#1d4ed8": "/productsImages/polarised-sunglasses-blue.png",
      "#facc15": "/productsImages/polarised-sunglasses-yellow.png",
    },
  },
  {
    id: 8,
    name: "Rockstar Jacket",
    price: 145.0,
    discount: 20,
    brand: "Vagabond",
    rating: 4.9,
    tags: ["Fashion", "Belt"],
    collection: "Best sellers",
    countInStock: 8,
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#facc15", name: "Yellow" },
    ],
    sizes: ["S", "M", "L"],
    imagesByColor: {
      "#000000": "/productsImages/rockstar-jacket-black.png",
      "#facc15": "/productsImages/rockstar-jacket-yellow.png",
    },
  },
  {
    id: 9,
    name: "Dotted Black Dress",
    price: 78.0,
    discount: null,
    brand: "Retrolie",
    rating: 4.6,
    tags: ["Fashion"],
    collection: "New arrivals",
    countInStock: 45,
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#f3f4f6", name: "White" },
    ],
    sizes: ["S", "M", "L", "XL"],
    imagesByColor: {
      "#000000": "/productsImages/dotted-black-dress-black.png",
      "#f3f4f6": "/productsImages/dotted-black-dress-white.png",
    },
  },
  {
    id: 10,
    name: "Linen Denim Summer Set",
    price: 115.0,
    discount: 15,
    brand: "Minimog",
    rating: 4.8,
    tags: ["Denim", "Hats", "Sunglasses", "Beachwear"],
    collection: "Best sellers",
    countInStock: 20,
    colors: [
      { hex: "#1d4ed8", name: "Blue" },
      { hex: "#a855f7", name: "Purple" },
      { hex: "#facc15", name: "Yellow" },
      { hex: "#f3f4f6", name: "White" },
    ],
    sizes: ["S", "M", "L"],
    imagesByColor: {
      "#1d4ed8": "/productsImages/linen-denim-summer-set-blue.png",
      "#a855f7": "/productsImages/linen-denim-summer-set-purple.png",
      "#facc15": "/productsImages/linen-denim-summer-set-yellow.png",
      "#f3f4f6": "/productsImages/linen-denim-summer-set-white.png",
    },
  },
  {
    id: 11,
    name: "Cozy Knit Sweater",
    price: 85.0,
    discount: null,
    brand: "Learts",
    rating: 4.6,
    tags: ["Fashion"],
    collection: "New arrivals",
    countInStock: 15,
    colors: [
      { hex: "#0ea5e9", name: "Sky" },
      { hex: "#6b7280", name: "Gray" },
    ],
    sizes: ["S", "M", "L", "XL"],
    imagesByColor: {
      "#0ea5e9": "/productsImages/cozy-knit-sweater-sky.png",
      "#6b7280": "/productsImages/cozy-knit-sweater-gray.png",
    },
  },
  {
    id: 12,
    name: "Glitter Off-Shoulder Dress",
    price: 95.0,
    discount: 10,
    brand: "Learts",
    rating: 4.9,
    tags: ["Fashion"],
    collection: "Best sellers",
    countInStock: 28,
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#6b7280", name: "Gray" },
    ],
    sizes: ["S", "M", "L"],
    imagesByColor: {
      "#000000": "/productsImages/glitter-off-shoulder-dress-black.png",
      "#6b7280": "/productsImages/glitter-off-shoulder-dress-gray.png",
    },
  },
  {
    id: 13,
    name: "Casual Streetwear Lounge Set",
    price: 110.0,
    discount: null,
    brand: "Vagabond",
    rating: 4.5,
    tags: ["Fashion", "Sunglasses"],
    collection: "New arrivals",
    countInStock: 16,
    colors: [
      { hex: "#f3f4f6", name: "White" },
      { hex: "#1e293b", name: "Dark" },
      { hex: "#78350f", name: "Brown" },
      { hex: "#0ea5e9", name: "Sky" },
    ],
    sizes: ["S", "M", "L", "XL"],
    imagesByColor: {
      "#f3f4f6": "/productsImages/streetwear-lounge-white.png",
      "#1e293b": "/productsImages/streetwear-lounge-black.png",
      "#78350f": "/productsImages/streetwear-lounge-brown.png",
      "#0ea5e9": "/productsImages/streetwear-lounge-sky.png",
    },
  },
];

export async function getProducts() {
  return Promise.resolve(products);
}
